### PR TITLE
RecipeFinder

### PR DESCRIPTION
**Pull request by shrehs**
Closes: #72 

- **Title**:  RecipeFinder
- **Your Name**: shrehs
- **Idenitfy yourself**:  GSSOC-Ext

### Describe the add-ons or changes you've made 📃
Made changes on function as it's dynamically called which had caused issues in input acceptance
Give a clear description of what have you added or modifications made
modified function name to resolve dynamic calling of the function as it would have accepted null as input
Added a button "Find Recipe" 

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

Screenshot (131)
Screenshot (133)
[Uploading recipeFinder2.webm…]()

### CODE REVIEW

**Comment by Zedoman** [comment]
Provide a video for the changes u have done

**Comment by shrehs** [comment]
[recipeFinder2.webm](https://github.com/user-attachments/assets/fef5af57-7f38-4095-b7ab-1318b08050cb)

**Review by Zedoman — DISMISSED** [review]

**Review by Avdhesh-Varshney — APPROVED** [review]

**Comment by Avdhesh-Varshney** [comment]
Never commit directly in main branch

**Comment by shrehs** [comment]
> Never commit directly in main branch

Sure, I'll remember that!

**Review by Zedoman — APPROVED** [review]

**Pull request merged**
