### PR TITLE
Added Speech to text program

### PR DESCRIPTION
**Pull request by jaidh01**
Closes: #191 

- **Title**:  Added Speech to text program
- **Your Name**:  Jai Dhingra
- **Idenitfy yourself**: GSSOC, Hacktoberfest 2024 Contributor) -->

### Describe the add-ons or changes you've made 📃

Created a new section under Programs sections, and created a file program.py file for this to check for errors, and add this in functions.py file so that we can see this in the streamlit application.

I added a program which enables to convert our speech into text in real time, with lowest latency.

NOTE: - Currently It works only on English language.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

https://github.com/user-attachments/assets/1048b75a-e97b-44cf-8edc-2f776b9ac4da

### CODE REVIEW

**Comment by jaidh01** [comment]
@Avdhesh-Varshney @Zedoman, any review or suggestion in this PR?

**Comment by Avdhesh-Varshney** [comment]
Sorry, this program is not accepted.

**Comment by jaidh01** [comment]
@Avdhesh-Varshney, I didn't get it, initially you assigned it to me, then I work on it, now you are saying it is not accepted??

Can you please tell me the reason.

**Comment by Avdhesh-Varshney** [comment]
At first, I'm thinking, it's a model. Now, I'm not thinking, it's not suitable for the project use case.

**Pull request closed without merging**
