### PR TITLE
Handwritten digit recognizer using CNN

### PR DESCRIPTION
**Pull request by payo101**
Closes: https://github.com/Avdhesh-Varshney/Jarvis/issues/63

- **Title**:  Handwritten Digit Recognition using CNN
- **Your Name**: Piyus Kumar Rout
- **Idenitfy yourself**: Hackotber Fest Contributor

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
- Added a lightweight CNN-based model for handwritten Image detection, trained on the MNIST dataset
- It has been integrated with the other Model Pages, as a drop-down under **Object Detection Model**

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

Screenshot 2024-10-04 174614

[streamlit-Jarvis-2024-10-04-17-10-99.webm](https://github.com/user-attachments/assets/f2c10056-b7f6-4558-b94a-fa06401e8bba)

### CODE REVIEW

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
- Model looks nice. 
- But don't create a new category. Keep it under Object Detection Models.
- Undo the changes in `.gitignore`. Just not upload those files which are un-necessary.

**Comment by Avdhesh-Varshney** [comment]
Attach your issue with the pr.

**Comment by payo101** [comment]
Alright cool
Will get that ready then

**Comment by payo101** [comment]
Could you have a look now @Avdhesh-Varshney

**Comment by jaidh01** [comment]
Hey @payo101, I just need a small help from you. Actually I have created a model in object detection and it is working properly when i run it separately, but when I am trying to run it with the complete application it is showing me a error.
Stated : - Module "filename.py" could not be found.
I have also attached the ss of it.

Screenshot (45)

**Comment by payo101** [comment]
@jaidh01 Sure,  Let's talk on discord for this, my discord id is payo_10

**Comment by jaidh01** [comment]
@payo101, check your Discord. I sent you a friend request over there.
My username is : - jai_dhingra_

**Review by Avdhesh-Varshney — APPROVED** [review]

**Review by Zedoman — APPROVED** [review]

**Pull request merged**
