### PR TITLE
feat : temperature details api program

### PR DESCRIPTION
**Pull request by akarshghildyal**
Closes: #49 

- **Title** : Temperature program
- **Name:** Akarsh Ghildyal
- **Idenitfy yourself:** SSOC Contributor

### Describe the add-ons or changes you've made 📃
I've made a temperature program that asks users to enter an api key and enter the name of the place to view its temperature details along with ```humidity, pressure, windspeed, condition, feels like temperature```
Give a clear description of what have you added or modifications made
I have utilised the [weather api](https://www.weatherapi.com/) to fetch the weather details of a place.

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

I ran the code locally.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

https://github.com/user-attachments/assets/4f5660e4-ffda-49cf-895f-f4c1805a4ec3

### Note to reviewers 📄

I had to crop the video(top and side) so I used an online editor so it has the watermark.

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@akarshghildyal until not assigned, don't raise the pr

**Comment by Avdhesh-Varshney** [comment]
rename `Temperature Details` to `Weather Details`

**Comment by akarshghildyal** [comment]
@Avdhesh-Varshney I am sorry, I was under the impression that I've been assigned the issue, I should've checked. 
I'll make the change now

**Comment by akarshghildyal** [comment]
> rename `Temperature Details` to `Weather Details`

done

**Review by Avdhesh-Varshney — APPROVED** [review]

**Pull request merged**
