### PR TITLE
add-anime-in-api-programs

### PR DESCRIPTION
**Pull request by nidhi2026**
Closes: #188 

- **Title**:  Add anime in api programs
- **Your Name**: Nidhi
- **Idenitfy yourself**: GSSOC-ext Contributor

### Describe the add-ons or changes you've made 📃

Added an anime under API programs

- Top 10 animes 
- Top 10 characters on MyAnimeList site
- Filter animes on the basis of order(rank/fav/popularity/etc), sort(asc/desc) and multiple genre select

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷
image

### CODE REVIEW

**Comment by Zedoman** [comment]
Provide a working video of the project @nidhi2026

**Comment by nidhi2026** [comment]
Here is a demo:

https://github.com/user-attachments/assets/4aba0c43-7122-4b18-a4fe-9bebb41fdf37

**Comment by nidhi2026** [comment]
@Zedoman I have attached a preview

**Review by Avdhesh-Varshney — APPROVED** [review]
LGTM.

**Review by Zedoman — APPROVED** [review]

**Pull request merged**
