### PR TITLE
TextSummarization  In continuation to PR #156

### PR DESCRIPTION
**Pull request by Peart-Guy**
Closes: #64

- **Title**:  Text Summarization NLP
- **Your Name**: Ankan
- **Idenitfy yourself**: GSSOC-24 EXTD , Hacktoberfest

### Describe the add-ons or changes you've made 📃
In continuation to PR #156 
Give a clear description of what have you added or modifications made
I have added the text summarization NLP model with all the file names correctly and Folder names correctly. 
Kindly Check it out

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by Peart-Guy** [comment]
@Avdhesh-Varshney  
I have done this new PR with 1 commit to make it easier to merge. Kindly check it out
and give GSSOC-24 EXTD , Hacktoberfest and level-3. It will be an honor.
Thank You

**Comment by Avdhesh-Varshney** [comment]
Looks good. But need a working integrated video with Jarvis before approving this pr.

**Comment by Peart-Guy** [comment]
> Looks good. But need a working integrated video with Jarvis before approving this pr.


@Avdhesh-Varshney 
Sure, Here is the video, KIndly check it out.

https://github.com/user-attachments/assets/c82dc65f-4881-4dd3-bcfb-9609df8d5596

**Review by Avdhesh-Varshney — APPROVED** [review]

**Review by Zedoman — APPROVED** [review]

**Comment by Peart-Guy** [comment]
@Avdhesh-Varshney @Avdhesh-Varshney 
Please give Level 3 as it took a lot of effort . It will be an honor.
Thank You

**Pull request merged**
