### PR TITLE
Recipe Finder

### LINKED ISSUE #72: 📃: Recipe Finder
:red_circle: **Title** : Recipe Finder  
:red_circle: **Aim** : Integrate a feature to search and display recipes based on user inputs in the Streamlit-based Jarvis application.  
:red_circle: **Brief Explanation** :  
- Utilize a recipe API to fetch recipes based on ingredients or dish names entered by the user.
- Implement a search functionality where users can input ingredients or dish names.
- Display relevant recipes including ingredients, cooking instructions, and possibly images.
- Ensure the UI is user-friendly and allows for easy browsing of recipes.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by shrehs**
Closes: #72 

- **Title**:  recipeFinder
- **Your Name**: Shreya H S
- **Idenitfy yourself**:  GSSOC contributor

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
This PR deals with the FirstReviewChanges of the earlier PR. Removed the .gitignore file added and restored the original .gitignore file. Used the st.secrets. Renamed the file according to the followed naming convention.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

[RecipeFinder.webm](https://github.com/user-attachments/assets/7c0dc055-8c64-4830-bad4-98b8bd43f75c)

Screenshot (131)
Screenshot (132)
Screenshot (133)

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
It looks good. But i want a video which is integrated with Jarvis. Start video from `Login` upto testing.

**Comment by shrehs** [comment]
> It looks good. But i want a video which is integrated with Jarvis. Start video from `Login` upto testing.

yeah, wanted to mention that I'm unable to run jarvis (I have followed the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md)] & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) ). I'll attach an image for my issue. Please do let me know how do I deal with the MongoDB_URI.
Screenshot (134)

**Comment by Avdhesh-Varshney** [comment]
I've created a discussion forum related to MONGODB setup. #176 If you still have any query, mention me there. It will be helpful for others.

**Comment by Avdhesh-Varshney** [comment]
What's the update?

**Comment by shrehs** [comment]
Hi, I have a created a new PR on this Please check it out, #195

**Pull request closed without merging**
