### PR TITLE
Added real-time object detection feature.

### PR DESCRIPTION
**Pull request by jaidh01**
Closes: #67 

- **Title**:  Real-time object detection in Videos
- **Your Name**: Jai Dhingra
- **Idenitfy yourself**: GSSOC-extd  Contributor

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

* Added the real-time object detection model using YOLO.
* Implemented : - 
1. Dynamic frame skipping, to stay around the desired FPS which is 30 FPS.
2. Multi-Thread processing to reduce processing time and increase the FPS.
3. Option to use GPU and half precision ( FP16 precision ).
4. The same code can be used with Yolo v8 models as well as Yolo v11 models.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

Screenshot (34)
Screenshot (35)

### CODE REVIEW

**Comment by jaidh01** [comment]
Hi @Avdhesh-Varshney,

I hope you're doing well! I have a small request—could you please add the gssoc-extd, hacktoberfest-accepted, and level labels to this PR? These labels are required for it to count toward my GSSOC-extended contributions.

Thank you for your time and support!

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
Integrate it properly with the streamlit application and attach a full screen working video of the application.
- Remove the un-necessary comments/code in the file.

**Comment by jaidh01** [comment]
Hi @Avdhesh-Varshney, 
This PR is ready for review.
Here is the working video: - 

https://github.com/user-attachments/assets/b037839c-edb9-4b82-a326-0adf0d25afd1

**Review by Avdhesh-Varshney — CHANGES_REQUESTED** [review]
You have committed your local python environment. Just commit the required files and delete others.

**Comment by Avdhesh-Varshney** [comment]
@jaidh01 you have mentioning everywhere related to filename issue. You can just write your function name in the python file in camelCase letters and same name is of fileName.

You should join the discord server where other contributors having same issue will help you to deal with it ok.
https://discord.gg/tSqtvHUJzE

**Comment by jaidh01** [comment]
Sorry for that, just trying to get help from the one who have done this.

I will join the discord.
Thank you for providing the link.

**Pull request closed without merging**
