### PR TITLE
upgraded live location detection and weather detection

### PR DESCRIPTION
**Pull request by Nayan2003**
Closes: #238 
upgraded live location detection and weather detection

- **Title**:  upgraded live location detection and weather detection
- **Your Name**:  Nayan khuje
- **Idenitfy yourself**: 
CONTRIBUTOR at GSSoC 24 Extd
### Describe the add-ons or changes you've made 📃
Hello admin , i added here 3 programs that one is taking local ip address and in 2nd program generating live location and 3rd detecting weather in current location , and main thing there is no API key for detecting location and weathere i hope you will like this

Give a clear description of what have you added or modifications made
I added Live location detection of user and Live weather detection of user (without using external any API)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

image

### CODE REVIEW

**Comment by Nayan2003** [comment]
bhai tu nahi karega assign 
...
i missed my 20 points

**Comment by Nayan2003** [comment]
bhai abb toh assign kar atleast dekh toh ek time
 my work

**Review by Avdhesh-Varshney — COMMENTED** [review]
- Never commit in `main` branch directly.
- No integration with `Jarvis` project.
- Attach a working video with your pr.

**Comment by Nayan2003** [comment]
ok

**Comment by Nayan2003** [comment]
What does mean of no integration with Jarvis project??

**Comment by Avdhesh-Varshney** [comment]
Review other merged prs to know about it

**Pull request closed without merging**
