### PR TITLE
feat: music player

### PR DESCRIPTION
**Pull request by akarshghildyal**
Closes: #46 

- **Title**:  #46 
- **Your Name**: Akarsh Ghildyal 
- **Idenitfy yourself**:  Hacktoberfest

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
So I used Spotify's web API and used a python library called [spotipy ](https://github.com/spotipy-dev/spotipy/blob/master/docs/index.rst) to integrate music/artist/album search and music play functionality. The API only allows around 30 seconds to play. It is free to create API from spotify so users can do it. I was not able to find a better free alternative hence decided to continue with Spotify's API.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

https://github.com/user-attachments/assets/635a8cb5-b03a-48f1-ac6f-db6bc204a22e

### CODE REVIEW

**Review by Avdhesh-Varshney — COMMENTED** [review]
It looks really cool. 
But play the music directly as entered the music names. Don't go to other tab. Try to resolve it and mention me again.

**Comment by akarshghildyal** [comment]
@Avdhesh-Varshney Added a play button under preview instead of redirecting to a new page.
I was muting and unmuting that is why there is sound and no sound in the demo, kindly excuse that.

https://github.com/user-attachments/assets/bc39e62d-ed2a-4e54-b6f9-8da0ffa3d222

**Comment by jaidh01** [comment]
hey @akarshghildyal, I just need a small help, actually I have created a model in object detection and it is working properly when i run it separately, but when I am trying to run it with the complete application it is showing me a error.
Stated : - Module "filename.py" could not be found.
I have also attached the ss of it.

Screenshot (37)

**Comment by akarshghildyal** [comment]
@jaidh01 can you tell me how did you name your file ? send me a ss if possible

**Comment by jaidh01** [comment]
> hey @akarshghildyal, I just need a small help, actually I have created a model in object detection and it is working properly when i run it separately, but when I am trying to run it with the complete application it is showing me a error. Stated : - Module "filename.py" could not be found. I have also attached the ss of it.
> 
> Screenshot (37)

@Avdhesh-Varshney Can you please help me a bit in this.

**Comment by akarshghildyal** [comment]
@Avdhesh-Varshney @Zedoman can you review and merge ?
and also add hacktoberfest relevant labels. Thank you.

**Review by Avdhesh-Varshney — APPROVED** [review]

**Review by Zedoman — APPROVED** [review]

**Pull request merged**
