### PR TITLE
Fixes findIP and myLocation to get session user's IP and other geo information

### PR DESCRIPTION
**Pull request by nidhi2026**
Closes: #174 

- **Title**:  Fixes findIP and myLocation to get session user's IP and other geo information
- **Your Name**:  Nidhi
- **Idenitfy yourself**:  GSSOC-ext Contributor

### Describe the add-ons or changes you've made 📃
Instead of directly calling `ipify` through requests (which was actually making request from streamlit server thus displaying its data), the changes includes using `javascript` to insert an `iframe` and display IP. Also included a copy button to copy IP address (IPV4 & IPV6)

for myLocation, as due to CORS policies, we can't directly get the IP address as variable in python code, so provided an input to input any IP, also displaying that user's IP, which they can copy-paste and get geo-info. And also allows user to have flexibility to input other IP addresses as well.

Tested the working by deploying on streamlit: https://ip-check.streamlit.app/

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/Contributing.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/Jarvis/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷
image
image

### CODE REVIEW

**Comment by nidhi2026** [comment]
@Avdhesh-Varshney 
I have made the pr.
If it is fine, then please label it with gssoc-ext and level. If not, should I make some changes.

**Comment by Avdhesh-Varshney** [comment]
Every pr before approving requires a proper working video to verify proper integration with Jarvis. You can hide your location by blurring them.

**Comment by nidhi2026** [comment]
Okie, 

https://github.com/user-attachments/assets/0dbd2b99-6e7e-4030-84d0-8ef9e80821c4

**Comment by nidhi2026** [comment]
> Every pr before approving requires a proper working video to verify proper integration with Jarvis. You can hide your location by blurring them.

Done

**Review by Avdhesh-Varshney — APPROVED** [review]

**Review by Zedoman — APPROVED** [review]

**Pull request merged**
